apiVersion: v1
kind: Service
metadata:
  name: mysql #Service的全局唯一名称
spec:
  type: NodePort
  ports:
  - port: 3306
    nodePort: 30000
  selector: #Service对应的Pod拥有这里定义的标签
    app: mysql
# https://raw.githubusercontent.com/zw23534572/alpine-addons/master/mysql/single/mysql-svc.yaml